# 파일 경로: apigateway-service/src/main/resources/application.yml

server:
  port: 8000

spring:
  application:
    name: apigateway-service

  # [통제 타워] Config Server 연결
  config:
    import: "optional:configserver:http://localhost:8888/"

  # ✅ [Safety Net] 중앙 통제 키 주입 (들여쓰기 교정 완료)
  token:
    secret: ${token.secret:user_token_native_jwt_secret_key_SHOUDL_BE_SAME_AND_VERY_LONG_VALUE_FOR_HS512}
    expiration_time: ${token.expiration_time:86400000}

  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 5000
      
      # [CORS] 프론트엔드 접속 허용 설정
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5500"
              - "http://127.0.0.1:5500"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      # [Routes] 엔터프라이즈 라우팅 규칙
      routes:
        # 1. [Member] 퍼블릭 통로 (로그인, 가입)
        - id: member-service-public
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/join, /api/v1/login
          filters:
            - name: CircuitBreaker
              args:
                name: memberCircuitBreaker
                fallbackUri: forward:/fallback/member

        # 2. [Member] 프라이빗 통로 (마이페이지 등)
        - id: member-service-secure
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/members/**, /member-service/**
          filters:
            - AuthorizationHeaderFilter # ✅ JWT 보안 필터 적용
            - name: CircuitBreaker
              args:
                name: memberCircuitBreaker
                fallbackUri: forward:/fallback/member

        # 3. [Catalog]
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/**, /api/v1/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: catalogCircuitBreaker
                fallbackUri: forward:/fallback/catalog

        # 4. [Order]
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**, /api/v1/orders/**
          filters:
            - AuthorizationHeaderFilter
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/fallback/order

        # 5. [Delivery]
        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/delivery-service/**, /api/v1/deliveries/**
          filters:
            - AuthorizationHeaderFilter

        # 6. [Payment]
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/**
          filters:
            - AuthorizationHeaderFilter
            - name: CircuitBreaker
              args:
                name: paymentCircuitBreaker
                fallbackUri: forward:/fallback/payment

  # [Redis] 세션 및 레이트 리밋용
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

# [Discovery] 유레카 등록
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://kimpro:1234@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# [Ops] 모니터링 및 갱신
management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway, refresh
  endpoint:
    gateway:
      enabled: true
