server:
  port: 8000

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 5000
      
      # [Routes] 이정표 설정
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            # 🚨 [Fix] 로그인(/login), 가입(/join) 경로 복구 완료
            - Path=/api/v1/join, /api/v1/login, /api/v1/members/**, /member-service/**, /actuator/**
          filters:
            - name: CircuitBreaker
              args:
                name: memberCircuitBreaker
                fallbackUri: forward:/fallback/member

        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/**, /api/v1/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: catalogCircuitBreaker
                fallbackUri: forward:/fallback/catalog

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**, /api/v1/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/fallback/order

        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/delivery-service/**, /api/v1/deliveries/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/**

        - id: search-service
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/search-service/**, /api/v1/search/**

        - id: batch-service
          uri: lb://BATCH-SERVICE
          predicates:
            - Path=/batch-service/**

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

# [Eureka]
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://kimpro:1234@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
