# ==============================================================================
# [Remote Config] API Gateway Service - Dynamic Configuration
# 이 파일은 GitHub에서 관리되며, 변경 시 서버 재배포 없이 /bus-refresh로 반영됩니다.
# ==============================================================================

# ✅ [Core] 포트 강제 지정 (Local 설정을 덮어쓰기 위함)
server:
  port: 8000

# 1. Spring Cloud Gateway 라우팅 & 필터
spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 5000
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET, POST, PUT, DELETE, OPTIONS
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
            - Path=/api/v1/members/**
          filters:
            - name: CircuitBreaker
              args:
                name: memberCircuitBreaker
                fallbackUri: forward:/fallback/member

        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/**
            - Path=/api/v1/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: catalogCircuitBreaker
                fallbackUri: forward:/fallback/catalog

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
            - Path=/api/v1/orders/**
          filters:
            - AuthorizationHeaderFilter
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/fallback/order
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1

        - id: search-service
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/search-service/**
            - Path=/api/v1/search/**

        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/delivery-service/**
            - Path=/api/v1/deliveries/**
          filters:
            - AuthorizationHeaderFilter

        - id: batch-service
          uri: lb://BATCH-SERVICE
          predicates:
            - Path=/batch-service/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/**
          filters:
            - AuthorizationHeaderFilter
            - name: CircuitBreaker
              args:
                name: paymentCircuitBreaker
                fallbackUri: forward:/fallback/payment

  # 2. Redis 설정 (환경변수 대응)
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

# 3. Jasypt & Security
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithHMACSHA512AndAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    pool-size: 2
    string-output-type: base64

token:
  # GitHub에 올라가지만 암호화되어 있어 안전함
  secret: ENC(5gtmaAozpeoVMs1gbym2Lt6S32ztOuqnUkaGG458uuYv8DIBuvvF1KBid6L5WQweh95w6TYjgLrzxyCQ/qsOtpGWzmdOY3QY9uq7JyjieyoYRN056Y368w8O1BkSiS8Cindl6C8GNKStrUISmfrUew==)

# 4. Resilience4j (Circuit Breaker & TimeLimiter)
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s

# 5. Management & Eureka
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, gateway, circuitbreakers

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
