server:
  port: 8082 # 랜덤 포트(0) 대신 고정 포트 권장

spring:
  cloud:
    compatibility-verifier:
      enabled: false

  # ✅ [Critical Fix] AWS RDS 연결 정보로 통일 (Member 서비스와 동일한 인프라 사용)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://adam-main-db.c9uycsosecd8.ap-northeast-2.rds.amazonaws.com:3306/adam_catalog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048
    username: kimpro
    password: kimpro032577

    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        jdbc.batch_size: 50

# [Eureka]
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://kimpro:1234@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    com.adam: INFO
